import { systemWeights } from 'react-native-typography';
export default {
  disabledOpacity: 0.5,
  roundness: 6,
  colors: {
    background: 'rgba(251, 252, 253, 1)',
    communityDarkUI: 'rgb(23, 24, 26)',
    communityPrimary: 'rgb(35, 197, 98)',
    communityPrimaryAlt: 'rgb(24, 103, 255)',
    divider: 'rgba(234, 237, 242, 1)',
    error: 'rgb(177, 67, 65)',
    light: 'rgb(247, 245, 241)',
    lightBackground: 'rgb(229, 237, 241)',
    lightBlue: 'rgb(187, 220, 225)',
    lightInverse: 'rgba(255, 255, 255, 0.68)',
    lightInverse: 'rgba(255, 255, 255, 0.68)',
    medium: 'rgb(68, 68, 68)',
    mediumInverse: 'rgba(255, 255, 255, 0.87)',
    mediumInverse: 'rgba(255, 255, 255, 0.87)',
    mediumLight: 'rgb(158, 158, 158)',
    primary: 'rgb(2, 84, 118)',
    secondary: 'rgb(245, 209, 95)',
    secondaryDark: 'rgb(239, 194, 41)',
    strong: 'rgb(51, 51, 51)',
    strongInverse: 'rgba(255, 255, 255, 1)',
    strongInverse: 'rgba(255, 255, 255, 1)',
    success: 'rgb(5, 168, 127)',
    surface: 'rgba(255, 255, 255, 1)',
  },
  typography: {
    body1: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    body2: {
      ...systemWeights.regular,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    button: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 16,
    },
    caption: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    headline1: {
      ...systemWeights.bold,
      fontSize: 60,
      letterSpacing: 0,
      lineHeight: 71,
    },
    headline2: {
      ...systemWeights.bold,
      fontSize: 48,
      letterSpacing: 0,
      lineHeight: 58,
    },
    headline3: {
      ...systemWeights.bold,
      fontSize: 34,
      letterSpacing: 0,
      lineHeight: 40,
    },
    headline4: {
      ...systemWeights.bold,
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 34,
    },
    headline5: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 0,
      lineHeight: 26,
    },
    headline6: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 24,
    },
    overline: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 2,
      lineHeight: 16,
    },
    subtitle1: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    subtitle2: {
      ...systemWeights.regular,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    custom14: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom15: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom16: {
      ...systemWeights.regular,
      fontSize: 14,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom17: {
      ...systemWeights.medium,
      fontSize: 14,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom18: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom19: {
      ...systemWeights.semibold,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom20: {
      ...systemWeights.semibold,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom21: {
      ...systemWeights.semibold,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom22: {
      ...systemWeights.semibold,
      fontSize: 12,
      letterSpacing: 2,
      lineHeight: 16,
    },
    custom23: {
      ...systemWeights.semibold,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom24: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom25: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 4,
      lineHeight: 16,
    },
    custom26: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom27: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom28: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom29: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom30: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 10,
      lineHeight: 24,
    },
    custom31: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom32: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 0,
    },
    custom33: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom34: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 1,
    },
    custom35: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom36: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom37: {
      ...systemWeights.medium,
      fontSize: 10,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom38: {
      ...systemWeights.medium,
      fontSize: 6,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom39: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom40: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom41: {
      ...systemWeights.medium,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom42: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
  },
};
